# Generated by Django 5.1.1 on 2024-09-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.TextField(max_length=255)),
                ('titulo', models.TextField(max_length=255)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
