# Generated by Django 5.1.1 on 2024-09-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificate_fill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
